load('ORLgammaae1k80191e4.mat');
% b = load('sORLgnmfgammak80191e4.mat');
gammaall = [1e-9, 2e-9, 3e-9, 4e-9, 5e-9, 6e-9, 7e-9, 8e-9, 9e-9,...
    1e-8, 2e-8, 3e-8, 4e-8, 5e-8, 6e-8, 7e-8, 8e-8, 9e-8,1e-7];

figure;
hold on;

% gnmfgamma = line(1:19,b.AccuracyG_ASCG);
gnmfdgamma = line(1:19, AccuracyGd_ASCG);

% set(gnmfgamma                     , ...
%   'Color'           , 'r'    , ...
%   'LineWidth'       , 1.5    , ...
%   'Marker'          , 'o'    , ...
%   'MarkerSize'      , 6      , ...
%   'MarkerEdgeColor' , 'r'    , ...
%   'MarkerFaceColor' , 'r'    );

set(gnmfdgamma               , ...
  'Color'           , 'b'    , ...
  'LineWidth'       , 1.5    , ...
  'Marker'          , '^'    , ...
  'MarkerSize'      , 5      , ...
  'MarkerEdgeColor' , 'b'    , ...
  'MarkerFaceColor' , 'b'    );

ylim([70,100])

set(gca                    ,...
    'xtick',1:20         ,...
    'xticklabel',[]);           %{'10^{-9}','10^{-8}','10^{-7}'});

text([1,10,19],repmat(68.8,1,3), ... % plot xlabel 
    {'10^{-9}' '10^{-8}' '10^{-7}'}, ...
    'hor','center')

hXLabel = xlabel('\gamma '                  );
hYLabel = ylabel('Accuracy(%)'              );

hLegend = legend(           ...
    gnmfdgamma           , ...
   'GNMFO'                 , ...
  'location', 'SouthEast' );
%   [gnmfgamma, gnmfdgamma]           , ...
%   'GNMF-ASCG'                  , ...
  

xlabh = get(gca,'XLabel');   % change xlabel position
set(xlabh,'Position',get(xlabh,'Position') - [0 1.7 0])


set(gcf, 'PaperPositionMode', 'auto');
print -depsc2 orlgamma.eps